services:
  lambda:
    image: node:lts-alpine
    volumes:
      - ./:/app
      - ~/.aws/credentials:/root/.aws/credentials
    working_dir: /app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run deploy:prod"
