org: guilhermedcdias10
service: workshop-auth

useDotenv: true

plugins:
  - serverless-offline

provider:
  name: aws
  region: us-east-1
  runtime: nodejs20.x
  # Using existing LabRole to avoid role creation issues in the Learner Lab
  role: arn:aws:iam::908171677883:role/LabRole
  # profile: fiap

  environment:
    JWT_SECRET: ${env:JWT_SECRET}
    POSTGRES_URL: ${env:POSTGRES_URL}

functions:
  api:
    handler: handler.handler
